;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "flux-integration")
(def path ".")
(def version "0.1.3")
(def tag "0.1.3")
(def generated-at "2021-01-04T23:24:26Z")
