;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "flux-integration")
(def path ".")
(def version "0.1.8")
(def tag "0.1.8")
(def generated-at "2021-01-16T07:17:43Z")
